# Generated by Django 3.2.4 on 2021-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='stok',
            field=models.IntegerField(null=True),
        ),
    ]
