# Generated by Django 3.2.4 on 2021-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0002_produk_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukti_pembayaran',
            name='dir_image',
            field=models.FileField(upload_to='dir_image'),
        ),
        migrations.AlterField(
            model_name='detail_produk',
            name='thumb_image',
            field=models.FileField(upload_to='thumbnail_produk'),
        ),
        migrations.AlterField(
            model_name='foto_produk',
            name='dir_foto',
            field=models.FileField(upload_to='foto_produk'),
        ),
        migrations.AlterField(
            model_name='nik',
            name='dir_nik',
            field=models.FileField(upload_to='ktp'),
        ),
    ]
