# Generated by Django 3.2.4 on 2021-07-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0003_auto_20210706_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto_produk',
            name='id_produk',
        ),
    ]
