# Generated by Django 3.2.4 on 2021-07-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0004_remove_foto_produk_id_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto_produk',
            name='id_produk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotoprodukid', to='webcosmoapp.produk'),
        ),
    ]
