# Generated by Django 3.2.4 on 2021-07-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0005_foto_produk_id_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_kategori',
            name='id_kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategorisubid', to='webcosmoapp.kategori'),
        ),
    ]
