# Generated by Django 3.2.4 on 2021-07-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0006_sub_kategori_id_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_produk',
            name='id_image',
        ),
    ]
