# Generated by Django 3.2.4 on 2021-07-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0007_remove_detail_produk_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='status',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
