# Generated by Django 3.2.4 on 2021-07-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0008_produk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='status',
            field=models.CharField(default='1', max_length=2, null=True),
        ),
    ]
