# Generated by Django 3.2.4 on 2021-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0009_alter_produk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='status',
            field=models.CharField(default='1', max_length=2, null=True),
        ),
    ]
