# Generated by Django 3.2.4 on 2021-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0010_kategori_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_kategori',
            name='status',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
