# Generated by Django 3.2.4 on 2021-07-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0012_produk_id_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='id_detail',
        ),
        migrations.AddField(
            model_name='detail_produk',
            name='kode_produk',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
