# Generated by Django 3.2.4 on 2021-07-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0013_auto_20210714_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='id_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_produkid', to='webcosmoapp.detail_produk'),
        ),
    ]
