# Generated by Django 3.2.4 on 2021-07-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0014_produk_id_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='jk',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
