# Generated by Django 3.2.4 on 2021-07-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0015_reseller_jk'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_reseller',
            name='tanggal_lahir',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
