# Generated by Django 3.2.4 on 2021-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0016_detail_reseller_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='dir_image',
            field=models.FileField(default='pp_reseller/default.png', upload_to='pp_reseller'),
        ),
    ]
