# Generated by Django 3.2.4 on 2021-07-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0017_reseller_dir_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_reseller',
            name='alamat_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_alamat_user', to='webcosmoapp.alamat'),
        ),
        migrations.AlterField(
            model_name='detail_reseller',
            name='id_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankid', to='webcosmoapp.account_bank'),
        ),
        migrations.AlterField(
            model_name='detail_reseller',
            name='id_nik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nikid', to='webcosmoapp.nik'),
        ),
    ]
