# Generated by Django 3.2.4 on 2021-07-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0018_auto_20210716_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alamat',
            old_name='keluarahan',
            new_name='kelurahan',
        ),
    ]
