# Generated by Django 3.2.5 on 2021-07-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0020_auto_20210716_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurir',
            name='status',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
