# Generated by Django 3.2 on 2021-07-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0021_kurir_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='id_alamat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='id_bank',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='id_pengiriman',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
