# Generated by Django 3.2 on 2021-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0022_auto_20210725_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukti_pembayaran',
            name='dir_image',
            field=models.FileField(upload_to='buktipembayaran'),
        ),
    ]
