# Generated by Django 3.2 on 2021-07-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0023_alter_bukti_pembayaran_dir_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='id_buktipem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pembayaranbuktipemid', to='webcosmoapp.bukti_pembayaran'),
        ),
    ]
