# Generated by Django 3.2 on 2021-07-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0024_alter_pembayaran_id_buktipem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengiriman',
            name='resi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pengiriman',
            name='tanggal_pengiriman',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
