# Generated by Django 3.2 on 2021-07-28 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcosmoapp', '0025_auto_20210726_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='pengirimanid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pengirimanid', to='webcosmoapp.pengiriman'),
        ),
    ]
